exai/ads/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'ads'

urlpatterns = [
    path('', views.index, name='index'),
    path('ads/<slug:pk>/', views.ads_detail),
]

exai/exai/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('ads.urls', namespace='ads')),
    path('admin/', admin.site.urls),
]

exai/ads/models.py
from django.db import models


class Car(models.Model):
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    photos = models.ForeignKey('Image', on_delete=models.CASCADE)
    release_date = models.DateField()
    mileage = models.IntegerField()
    engine_number = models.CharField(max_length=100)
    fuel = models.ForeignKey('Fuel', on_delete=models.CASCADE)
    transmission_type = models.ForeignKey('Transmission', on_delete=models.CASCADE)
    drive_type = models.ForeignKey('Drive', on_delete=models.CASCADE)
    configuration = models.ForeignKey('Configuration', on_delete=models.CASCADE)
    advertisement_link = models.URLField()

    def __str__(self):
        return f"{self.brand} {self.model}"


class Transmission(models.Model):
    type = models.CharField(max_length=100)

    def __str__(self):
        return self.type


class Drive(models.Model):
    type = models.CharField(max_length=100)

    def __str__(self):
        return self.type


class Configuration(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Image(models.Model):
    link = models.CharField(max_length=1000)


class Fuel(models.Model):
    type = models.CharField(max_length=20)

exai/ads/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Car


# Главная страница
def index(request):
    cars = Car.objects.order_by('-mileage')
    context = {
        'cars': cars
    }
    template = 'ads/index.html'
    return render(request, template, context)


def ads_detail(request, pk):
    return HttpResponse(f'Автомобиль номер {pk}')

exai/templates/ads/ads_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  Пост {{ post|truncatechars:30 }}
{% endblock%}

{% block content %}
<div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if group %}
              <li class="list-group-item">
                Группа: {{ group }}

                {% if post.group %}   
                  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
                {% endif %}


              </li>
            {% endif %}
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }} {{ post.author }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора: {{ author_posts_count }}
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text }}
          </p>

          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
            редактировать запись
          </a>


        </article>
    </div>


    {% load user_filters %}

    {% if user.is_authenticated %}
      <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
          <form method="post" action="{% url 'posts:add_comment' post.id %}">
            {% csrf_token %}      
            <div class="form-group mb-2">
              {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
          </form>
        </div>
      </div>
    {% endif %}
    
    {% for comment in comments %}
      <div class="media mb-4">
        <div class="media-body">
          <h5 class="mt-0">
            <a href="{% url 'posts:profile' comment.author.username %}">
              {{ comment.author.username }}
            </a>
          </h5>
            <p>
             {{ comment.text }}
            </p>
          </div>
        </div>
    {% endfor %} 

{% endblock content%}

exai/templates/ads/index.html
{% extends 'base.html' %}

{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
  
  <div class="container"> 
    <h1>Последние обновления на сайте</h1>

    {% for car in cars %}
      <ul>
        <li>
          Название: {{ car.brand }} {{car.model}}
        </li>
        <li>
          Стоимость: {{ car.cost }}
        </li>
      </ul>
      
      {% if car.photos %}
        <img src="{{ car.photos.link }}" alt="Car Image">
      {% else %}
        <p>No image available</p>
      {% endif %}

      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
{% endblock %}

exai/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
     {% block title %}
        Имя страницы
     {% endblock %}
    </title>
  </head>
  <body>   
    <header>
    {% block header %}
      {% include 'includes/header.html' %}
    {% endblock %}
    </header>

    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
    <footer class="page-footer font-small blue border-top">
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 

exai/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
  </footer> 

exai/templates/includes/header.html
{% load static %}

<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'ads:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      {% with request.resolver_match.view_name as view_name %}
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
          href="{% url 'ads:index' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" 
          href="{% url 'ads:index' %}">Технологии</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
          href="{% url 'ads:index' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'users:password_change_form' %}active{% endif %}"
          href="{% url 'ads:index' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'users:logout' %}active{% endif %}"
          href="{% url 'ads:index' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}"
          href="{% url 'ads:index' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}"
          href="{% url 'ads:index' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
      {% endwith %}   
    </div>
  </nav>      
</header>